### PR TITLE
Is this better than using switch?

### PR DESCRIPTION
**Pull request by TheAlemazing**

### CODE REVIEW

**Comment by huytd** [comment]
Looks good but I have a concern about simplicity. It might make the code shorter but maintainability is also a critical part, personally, I want to write simple code that allows any developer at any level could understand at the first glance.

**Comment by huytd** [comment]
Maybe we can apply this technique in some other place of the code, I think there is a lot of other place that need this in the codebase rather than this simple component.

**Comment by TheAlemazing** [comment]
If it is good enough for this simple component then we can merge it. We can apply to another component when we have time, no problem. 👍

**Comment by TheAlemazing** [comment]
any update?

**Comment by lqt93** [comment]
Thank you for your suggestion but as @huytd said above, this component is quite simple and doesn't need to have more efforts on it at the moment. In addition, using object literal like that might cause unexpected mistakes in case the component has its params changes. It can be said that, we will choose a safe style of code rather than a fancy one. To clarify the way we write code, I think we would make a code style convention in this project soon.

I will close this PR here. If you have any ideas to help us work better please feel free to open an issue and we can discuss more. And there are still lots of issues need to take care, I hope that you can help us by taking one of them.

**Pull request closed without merging**
